### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by Hanskes** [falk0069/sony-pm-alt#8]
i get the following when starting the python script sony-pm-alt.py (gphoto2 -P --port ptpip:192.168.178.20 --skip-existing works perfect):

python sony-pm-alt.py
2017-10-24 21:02:16,562 [INFO ] Server starting
2017-10-24 21:02:16,562 [INFO ] Setting download dir [PHOTO_DIR] to: /home/hans/
2017-10-24 21:02:16,562 [INFO ] Setting LD_LIBRARY_PATH to: /usr/local/lib

2017-10-24 21:02:18,750 [INFO ] received MtpNullService from ('192.168.178.20', 1900)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "sony-pm-alt.py", line 165, in run
    PROC = subprocess.Popen(GPHOTO_CMD_ARGS)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by falk0069** [comment]
Hi Hanskes,
The script by default assumes the gphoto2 exists here: `/usr/local/bin/gphoto2`.   I'm guessing it is located somewhere else for you.  Run this to find the path you are using: `which gphoto2`
Then edit line 16 of `sony-pm-alt.py` and use your path instead.  If that doesn't work for you, let me know what the `which gphoto2` command produced and also include the first 24 lines of `sony-pm-alt.py`.  Let me know how it goes.
